name: Deploy website to Cloudflare pages

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
      artifact-path:
        required: true
        type: string
      project-name:
        required: true
        type: string
      deployment-environment:
        required: true
        type: string
    secrets:
      account-id:
        required: true
      api-token:
        required: true

jobs:
  deploy:
    name: Deploy website
    runs-on: ubuntu-latest

    outputs:
      url: ${{ steps.deploy.outputs.deployment-url }}

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v8
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}

      - id: deploy
        name: Deploy to Cloudflare pages
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.api-token }}
          accountId: ${{ secrets.account-id }}
          command: pages deploy build --project-name=${{ inputs.project-name }} --branch=${{ inputs.deployment-environment }}
