name: Push to main branch

on:
  push:
    branches:
      - main

env:
  ARTIFACT_NAME: build_${{ github.ref_name }}_${{ github.sha }}
  ARTIFACT_PATH: dist

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    with:
      artifact-name: ${{ vars.ARTIFACT_NAME }}
      artifact-path: ${{ vars.ARTIFACT_PATH }}

  cd:
    needs: ci
    uses: ./.github/workflows/cd.yml
    permissions:
      pages: write
      id-token: write
    with:
      artifact-name: ${{ vars.ARTIFACT_NAME }}
      artifact-path: ${{ vars.ARTIFACT_PATH }}
