name: Push to main branch

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    with:
      artifact-name: build_${{ github.ref_name }}_${{ github.sha }}
      artifact-path: dist

  cd:
    name: CD
    needs: ci
    uses: ./.github/workflows/cd.yml
    permissions:
      pages: write
      id-token: write
    with:
      artifact-name: ${{ needs.ci.outputs.artifact-name }}
      artifact-path: ${{ needs.ci.outputs.artifact-path }}
