name: Push to secondary branch

on:
  push:
    branches-ignore:
      - main

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    with:
      artifact-name: build_${{ github.ref_name }}_${{ github.sha }}
      artifact-path: dist
