name: Push to main branch

on:
  push:
    branches:
      - main

env:
  artifact-name: build_${{ github.ref_name }}_${{ github.sha }}
  artifact-path: dist

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    with:
      artifact-name: ${{ vars.artifact-name }}
      artifact-path: ${{ vars.artifact-path }}

  cd:
    needs: ci
    uses: ./.github/workflows/cd.yml
    permissions:
      pages: write
      id-token: write
    with:
      artifact-name: ${{ vars.artifact-name }}
      artifact-path: ${{ vars.artifact-path }}
