name: Push to secondary branch

on:
  push:
    branches:
      - dev

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    with:
      artifact-name: build_${{ github.ref_name }}_${{ github.sha }}
      artifact-path: dist

  cd:
    name: CD
    needs: ci
    uses: ./.github/workflows/deploy-cloudflare-pages.yml

    environment:
      name: cf-preview
      url: ${{ jobs.cd.outputs.url }}

    with:
      artifact-name: ${{ needs.ci.outputs.artifact-name }}
      artifact-path: ${{ needs.ci.outputs.artifact-path }}
      project-name: ${{ vars.CLOUDFLARE_ENVIRONMENT }}
      deployment-environment: ${{ vars.CLOUDFLARE_ENVIRONMENT }}
      account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
